server:
  port: 8888
spring:
  application:
    name: 地下车库引导系统
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: root
    url: jdbc:mysql://172.20.10.11:3306/car?characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    port: 8000
    password: redis123456
    host: 172.20.10.11
    database: 1
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    xyz:
      wuhen:
        car: debug